cabal-version:      3.4
name:               analyze-smt2
version:            0.1.0.0
license:            MIT
author:             Sören Tempel
maintainer:         tempel@ibr.cs.tu-bs.de
build-type:         Simple
copyright:          (c) 2025 Technische Universität Branuschweig

common warnings
    ghc-options: -Wall -O3

executable analyze-smt2
    import:           warnings
    main-is:          Main.hs
    build-depends:    base,
                      mtl,
                      containers,
                      simple-smt
    default-language: GHC2021
