cabal-version:      3.4
name:               smt-analyze
version:            0.1.0.0
license:            MIT
author:             Sören Tempel
maintainer:         tempel@ibr.cs.tu-bs.de
build-type:         Simple
copyright:          (c) 2025-2026 Technische Universität Branuschweig

common opts
    ghc-options: -Wall -O3

executable smt-analyze
    import:           opts
    main-is:          Main.hs
    build-depends:    base,
                      mtl,
                      containers,
                      simple-smt >= 1.0.1 && <1.1
    default-language: GHC2021
